In [1]:
import pandas as pd
import numpy as np

In [2]:
classes = ['faster', 'slower', 'easy-turn-right', 'still', 'easy-turn-left']

In [4]:
csv_path = f"../lololol/data/datasets/rounD-dataset-v1.0/data/" + "00"+ "_tracks.csv"
csv_path_meta = f"../lololol/data/datasets/rounD-dataset-v1.0/data/" + "00"+ "_tracksMeta.csv"

In [5]:
df1 = pd.read_csv(csv_path)
df1_meta = pd.read_csv(csv_path_meta)

In [6]:
df1_meta = df1_meta[['trackId', 'class']]

In [8]:
merged = df1.reset_index().merge(df1_meta.reset_index(), on=['trackId'])

In [12]:
truck_id = 26

In [14]:
from read_data import *

In [15]:
one_frame_df = merged[merged['frame'] == 0]

In [18]:
grouped_frame = one_frame_df.groupby([FRAME], sort=False)
tracks = {}
for group_id, rows in grouped_frame:
    bounding_boxes = np.transpose(np.array([rows[X].values,
                                            rows[Y].values,
                                            rows[WIDTH].values,
                                            rows[LENGHT].values]))

    tracks[np.int64(group_id)] = {
        TRACK_ID: rows[TRACK_ID].values,
        FRAME: rows[FRAME].values,
        X: rows[X].values,
        Y: rows[Y].values,
        BBOX: bounding_boxes,
        X_VELOCITY: rows[X_VELOCITY].values,
        Y_VELOCITY: rows[Y_VELOCITY].values,
        X_ACCELERATION: rows[X_ACCELERATION].values,
        Y_ACCELERATION: rows[Y_ACCELERATION].values,
        TRACKLIFETIME: rows[TRACKLIFETIME].values,
        HEADING: rows[HEADING].values,
        LONVELOCITY: rows[LONVELOCITY].values,
        LATVELOCITY: rows[LATVELOCITY].values,
        LONACCELERATION: rows[LONACCELERATION].values,
        LATACCELERATION: rows[LATACCELERATION].values,


    }

In [20]:
len(grouped_frame)

1

In [22]:
from check_dist import *

In [27]:
l = []
for j,i in enumerate(tracks):
    dist = create_distance_matrix(tracks[i])
    d = {FRAME: i, 'dist': dist}
    l.append(d)

In [31]:
all_frame = []
for num in range(len(l)):
    frame_id = l[num][FRAME]
    dist = l[num]['dist']

    for i, j in enumerate(dist['id']):
        sort_dist_index = np.argsort(dist['distance_matrix'][i])
        count = len(sort_dist_index)
        d = {'trackId': j,  'frame': frame_id,}

        for k in range(4):

            if k == 0:
                continue
            if k >= count:
                dict_dist = {f'{k}_yVelocity': 999999,
                             f'{k}_xVelocity': 999999,
                            f'{k}_yAcceleration': 999999,
                            f'{k}_xAcceleration': 999999,
                            f'{k}_xCenter': 999999,
                            f'{k}_yCenter': 999999,
                             f'{k}_distance': 999999}
            else:

                df = merged[(merged['frame'] == frame_id) & (merged['trackId'] == j)]
                dict_dist = {f'{k}_yVelocity': df['yVelocity'].values[0],
                            f'{k}_xVelocity': df['xVelocity'].values[0],
                            f'{k}_yAcceleration': df['yAcceleration'].values[0],
                            f'{k}_xAcceleration': df['xAcceleration'].values[0],
                            f'{k}_xCenter': df['xCenter'].values[0],
                            f'{k}_yCenter': df['yCenter'].values[0],
                             f'{k}_distance': dist['distance_matrix'][i][k] ,}
            d.update(dict_dist)


        all_frame.append(d)

In [33]:
df_all_frame = pd.DataFrame(all_frame)

In [36]:
df_all_frame

,trackId,frame,1_yVelocity,1_xVelocity,1_yAcceleration,1_xAcceleration,1_xCenter,1_yCenter,1_distance,2_yVelocity,...,2_xCenter,2_yCenter,2_distance,3_yVelocity,3_xVelocity,3_yAcceleration,3_xAcceleration,3_xCenter,3_yCenter,3_distance
0,23,0,-5.5759,0.8937,0.5016,2.2879,106.5811,-71.3164,0.007444,-5.5759,...,106.5811,-71.3164,0.011583,-5.5759,0.8937,0.5016,2.2879,106.5811,-71.3164,0.015072
1,24,0,10.1385,-2.6770,0.0783,0.6263,128.6583,-121.0474,0.000000,10.1385,...,128.6583,-121.0474,0.000458,10.1385,-2.6770,0.0783,0.6263,128.6583,-121.0474,0.003693
2,25,0,9.6526,-3.1941,0.9489,0.2387,133.5737,-137.1928,0.000458,9.6526,...,133.5737,-137.1928,0.000000,9.6526,-3.1941,0.9489,0.2387,133.5737,-137.1928,0.003094
3,26,0,-0.3041,2.9760,-0.1261,0.1326,89.8237,-75.5223,0.003693,-0.3041,...,89.8237,-75.5223,0.003094,-0.3041,2.9760,-0.1261,0.1326,89.8237,-75.5223,0.000000
4,342,0,-0.0000,0.0000,-0.0000,0.0000,128.4705,-103.8538,0.001263,-0.0000,...,128.4705,-103.8538,0.003229,-0.0000,0.0000,-0.0000,0.0000,128.4705,-103.8538,0.006204
5,343,0,-0.0000,0.0000,-0.0000,0.0000,129.5535,-109.2555,0.000671,-0.0000,...,129.5535,-109.2555,0.002230,-0.0000,0.0000,-0.0000,0.0000,129.5535,-109.2555,0.005309
6,344,0,-0.0000,0.0000,-0.0000,0.0000,131.1077,-115.3289,0.000204,-0.0000,...,131.1077,-115.3289,0.001238,-0.0000,0.0000,-0.0000,0.0000,131.1077,-115.3289,0.004040
7,345,0,-0.0000,0.0000,-0.0000,0.0000,133.3789,-124.1888,0.000009,-0.0000,...,133.3789,-124.1888,0.000555,-0.0000,0.0000,-0.0000,0.0000,133.3789,-124.1888,0.003546
8,346,0,-0.0000,0.0000,-0.0000,0.0000,135.3296,-131.3455,0.000213,-0.0000,...,135.3296,-131.3455,0.000093,-0.0000,0.0000,-0.0000,0.0000,135.3296,-131.3455,0.002624
9,347,0,-0.0000,0.0000,-0.0000,0.0000,137.5635,-138.0002,0.000271,-0.0000,...,137.5635,-138.0002,0.000030,-0.0000,0.0000,-0.0000,0.0000,137.5635,-138.0002,0.002933

In [37]:
one_frame_df2 = one_frame_df.reset_index().merge(df_all_frame.reset_index(), on=['trackId', 'frame'])

In [39]:
one_frame_df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10 entries, 0 to 9
Data columns (total 43 columns):
index_x            10 non-null int64
index_x            10 non-null int64
recordingId        10 non-null int64
trackId            10 non-null int64
frame              10 non-null int64
trackLifetime      10 non-null int64
xCenter            10 non-null float64
yCenter            10 non-null float64
heading            10 non-null float64
width              10 non-null float64
length             10 non-null float64
xVelocity          10 non-null float64
yVelocity          10 non-null float64
xAcceleration      10 non-null float64
yAcceleration      10 non-null float64
lonVelocity        10 non-null float64
latVelocity        10 non-null float64
lonAcceleration    10 non-null float64
latAcceleration    10 non-null float64
index_y            10 non-null int64
class              10 non-null object
index_y            10 non-null int64
1_yVelocity        10 non-null float64
1_xVelocity        10 non-null float64
1_yAcceleration    10 non-null float64
1_xAcceleration    10 non-null float64
1_xCenter          10 non-null float64
1_yCenter          10 non-null float64
1_distance         10 non-null float64
2_yVelocity        10 non-null float64
2_xVelocity        10 non-null float64
2_yAcceleration    10 non-null float64
2_xAcceleration    10 non-null float64
2_xCenter          10 non-null float64
2_yCenter          10 non-null float64
2_distance         10 non-null float64
3_yVelocity        10 non-null float64
3_xVelocity        10 non-null float64
3_yAcceleration    10 non-null float64
3_xAcceleration    10 non-null float64
3_xCenter          10 non-null float64
3_yCenter          10 non-null float64
3_distance         10 non-null float64
dtypes: float64(34), int64(8), object(1)
memory usage: 3.4+ KB

In [40]:
column3 = ['trackLifetime', 'xCenter', 'yCenter', 'heading', 'width', 'length', 'xVelocity', 'yVelocity', 
         'xAcceleration', 'yAcceleration', 'lonVelocity','latVelocity', 'lonAcceleration', 'latAcceleration', 
          '1_yVelocity', '1_xVelocity', '1_yAcceleration', '1_xAcceleration', '1_xCenter', '1_yCenter',
           '2_yVelocity', '2_xVelocity', '2_yAcceleration', '2_xAcceleration', '2_xCenter', '2_yCenter',
           '3_yVelocity', '3_xVelocity', '3_yAcceleration', '3_xAcceleration', '3_xCenter', '3_yCenter',
          '3_distance', '2_distance', '1_distance']

In [49]:
X = one_frame_df2[one_frame_df2['trackId'] == truck_id]
X = X[column3]

In [50]:
X

,trackLifetime,xCenter,yCenter,heading,width,length,xVelocity,yVelocity,xAcceleration,yAcceleration,...,2_yCenter,3_yVelocity,3_xVelocity,3_yAcceleration,3_xAcceleration,3_xCenter,3_yCenter,3_distance,2_distance,1_distance
3,0,89.8237,-75.5223,352.8856,3.2157,17.7394,2.976,-0.3041,0.1326,-0.1261,...,-75.5223,-0.3041,2.976,-0.1261,0.1326,89.8237,-75.5223,0.0,0.003094,0.003693

In [43]:
from joblib import dump, load
clf = load('truck_round.joblib')

In [44]:
clf

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=3,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=42, splitter='best')

In [51]:
y_pred=clf.predict(X)

In [53]:
classes[y_pred[0]]

'slower'